org.gradle.jvmargs=-Xmx2G
org.gradle.daemon=false
org.gradle.parallel=true
org.gradle.caching=true

# Environment
minecraft_version=1.21.1
minecraft_version_range=[1.21.1,1.22)
neo_version=21.1.248
neo_version_range=[21.1.0,)
loader_version_range=[4,)

# Mod
mod_id=mobhealthmodifier
mod_name=Mob Health Modifier
mod_license=MIT
mod_version=1.0.0
mod_group_id=com.marc33.mobhealth
mod_authors=Marc33
mod_description=Multiplie la sante et les degats des mobs hostiles, passifs ou de tous les mobs, via un fichier de configuration TOML.
